### ISSUE TITLE
Missing pybids compatibility: entity keywords in get do not match

### ISSUE THREAD

**Issue by lmichalke** [ANCPLabOldenburg/ancp-bids#10]
When calling get() on a BIDSLayout, the keywords in ancp-bids do not match the keywords in pybids (e.g. sub instead of subject). Naming the entity keywords in get() after the corresponding entities in the BIDS specification is more intuitive/user-friendly than having some of them written out and some abbreviated. ancp-bids does the keyword naming better, but the keywords that are different in pybids should be mapped to the right keywords in ancp-bids in addition, so that users can migrate their code from pybids without changes.

**Comment by erdalkaraca** [comment]
The provided entity keys/names are now recognized even if abbreviated or inflected (for example, subject vs subjects).

**Comment by erdalkaraca** [comment]
see unit test: tests.tests_schema.SchemaTestCase.test_entitmatching
