### ISSUE TITLE
issues in tests

### ISSUE THREAD

**Issue by ancpJR** [ANCPLabOldenburg/ancp-bids#15]
******
base_test_case.py seems to refer to variable definitions and data not contained in the repo

folder does not exist:BIDS_SCHEMA_DIR = "../../bids-specification/src/schema/"

     4 BIDS_SCHEMA_DIR = "../../bids-specification/src/schema/"
----> 5 TEST_FOLDER = os.path.dirname(__file__)
      6 RESOURCES_FOLDER = TEST_FOLDER + "/data"

NameError: name '__file__' is not defined

**********************
simple install with pip install ancpbids does not install lxml dependecy 
installing lxml with conda after nitsalling mne does not work due to conflicts
installing lxml with pip does work though

conda install regex workssoll 

***************************
tests_schema.py fails:
ModuleNotFoundError                       Traceback (most recent call last)
~/DDATA/Programming/Python/ancp-bids/tests/tests_schema.py in <module>
      2 
      3 from ancpbids import Schema
----> 4 from tests.base_test_case import BaseTestCase
      5 
      6 

ModuleNotFoundError: No module named 'tests.base_test_case'

********************************
test_writing.py fails with:
ModuleNotFoundError                       Traceback (most recent call last)
~/DDATA/Programming/Python/ancp-bids/tests/tests_schema.py in <module>
      2 
      3 from ancpbids import Schema
----> 4 from tests.base_test_case import BaseTestCase
      5 
      6 

ModuleNotFoundError: No module named 'tests.base_test_case'

**Comment by erdalkaraca** [comment]
@ancpJR thanks for reporting! Removed invalid module import. Sometimes the IDE is more intelligent than it should be and can handle such situations on its own :-)
