### ISSUE TITLE
Make validation BIDS version sensitive

### ISSUE THREAD

**Issue by ancpJR** [ANCPLabOldenburg/ancp-bids#37]
Currently only BIDS version <=1.7 is supported. Can we make the software aware of the dataset BIDS version. May not be a problem as long as the schema BIDS is backward compatible.

**Comment by erdalkaraca** [comment]
TODOs:
- embed the version in YAML schema
- check whether a dataset has a version defined and validate it against schema version, else assume the dataset uses the latest supported BIDS spec

**Comment by erdalkaraca** [comment]
Implemented in latest version:
- validation is sensitive to the BIDSVersion field in dataset_description.json
- if no supported version specified (anything below 1.7.0), then the earliest supported version is assumed
