### ISSUE TITLE
Output of the load_contents() function

### ISSUE THREAD

**Issue by AaronReer** [ANCPLabOldenburg/ancp-bids#41]
Currently the output of the load_contents() function is a numpy array. However when inspecting the contents of tabular files dataframes could be advantegous due to the header information which are omitted in numpy arrays.

**Comment by erdalkaraca** [comment]
Decision for numpy was by purpose: as less heavyweight dependencies as possible.
To reduce even the dependency to numpy, load_contents() could return an ordinary Python dict with  the headers and a 2D array:

contents = file.load_contents()

{
  headers: ['col1', 'col2', 'col3']
  data: [
    [3, 6, 1],
    [1, 5, 3],
    ...
  ]
}

At the same time, there could be a dynamic mechanism to load the file contents in a format that the caller/user wishes:

`file.load_contents(hints=['pandas', 'numpy'])`

this would be interpreted as to return a pandas dataframe if pandas is installed or numpy if numpy is installed
