### ISSUE TITLE
Configure project for setuptools for automated deployment on pypi.org

### ISSUE THREAD

**Issue by erdalkaraca** [ANCPLabOldenburg/ancp-bids#5]
Goal: enable uploading ancbids package on pypi.org

**Comment by tsalo** [comment]
Using a GitHub Action to publish each release automatically really streamlines my own workflow. [Here](https://github.com/ME-ICA/template-package/blob/main/.github/workflows/python-publish.yml) is a version that works for me in multiple packages. You could also probably replace the PYPI username and password secrets with a token secret.

It seems like you have all of the other packaging stuff set up. Is there anything in particular that needs to be done?

**Comment by erdalkaraca** [comment]
Thanks for the link, @tsalo, that was the missing hint to get started with GitHub Actions to automate the deployment 👍

**Comment by tsalo** [comment]
One warning- the Action only works for existing projects, so you'll need to upload the first version to PyPi locally in order to get things moving.

**Comment by erdalkaraca** [comment]
@tsalo I used your publish action as a template to automate deployment on new releases.
Thanks!
