### ISSUE TITLE
Remove dependency on numpy

### ISSUE THREAD

**Issue by ghisvail** [ANCPLabOldenburg/ancp-bids#56]
It looks like `ancpbids` only uses `numpy` to [parse TSV files](https://github.com/ANCPLabOldenburg/ancp-bids/blob/862ad86ada396789d62158ff9dcd64715698b135/ancpbids/plugins/plugin_files_handlers.py#L30).

I wonder whether the implementation could use the `csv` module instead, in order to drop the runtime requirement on `numpy`. This would strengthen the argument made for `ancpbids` being lightweight in the project description.

That would not prevent any client code to store the output from the CSV parser in a more efficient data structure tailored to their needs, whether it is a `numpy.ndarray`, a `pandas.DataFrame` or something else.

**Comment by erdalkaraca** [comment]
@ghisvail thanks for the proposal!

https://github.com/ANCPLabOldenburg/ancp-bids/issues/41 was also about the return type of the load_contents() function.

Do you have a suggestion for how the returned object should be structured?

**Comment by ghisvail** [comment]
> The list of records is the solution providing the best interop

I stand corrected, numpy's record constructors do not handle array of dicts the same way pandas does.

So in the end, it boils down to whether you want to optimize the loader for one particular solution (`numpy` or `pandas`), or adapt the output based on a parameter like suggested in #41.

For the latter, it's basically a matter of returning a dictionary with a different set of keys, i.e. `{"data": ..., "columns": ...}` for pandas and `{"recList": ..., "names": ...}` for numpy. Chaining could be achieved by means of:

```python
# NumPy
numpy.core.records.fromrecords(**load_contents(..., hint="numpy"))

# Pandas
pandas.DataFrame(**load_contents(..., hint="pandas"))
```

I have got an implementation that passes the test suite for the Numpy case. Happy to deal with the Pandas case if you want.

**Comment by erdalkaraca** [comment]
Sounds great, looking forward to reviewing the PR!

> > The list of records is the solution providing the best interop
> 
> I stand corrected, numpy's record constructors do not handle array of dicts the same way pandas does.
> 
> So in the end, it boils down to whether you want to optimize the loader for one particular solution (`numpy` or `pandas`), or adapt the output based on a parameter like suggested in #41.
> 
> For the latter, it's basically a matter of returning a dictionary with a different set of keys, i.e. `{"data": ..., "columns": ...}` for pandas and `{"recList": ..., "names": ...}` for numpy. Chaining could be achieved by means of:
> 
> ```python
> # NumPy
> numpy.core.records.fromrecords(**load_contents(..., hint="numpy"))
> 
> # Pandas
> pandas.DataFrame(**load_contents(..., hint="pandas"))
> ```
> 
> I have got an implementation that passes the test suite for the Numpy case. Happy to deal with the Pandas case if you want.

**Comment by erdalkaraca** [comment]
Maybe, one optimization: the hint could also be used to return an ndarray/DataFrame directly, so the user/caller does not need to manually do this.

**Comment by erdalkaraca** [comment]
Sounds great!
Do we need to catch the ImportError? I would just let it bubble up to the caller. Or what would you return in case the packages are not installed?

**Comment by ghisvail** [comment]
>  Do we need to catch the ImportError? I would just let it bubble up to the caller.

Only if you want to raise an exception with a friendlier error message. Otherwise, we can just get rid of the try / catch block and let the generic `ImportError` do the work.

> Or what would you return in case the packages are not installed?

If the caller explicitly asked for a `dataframe` and pandas is not available, I think it's better to raise an exception than returning something else.

**Comment by ghisvail** [comment]
I filed #57 to show how the code would look like.

However, I am having a hard time getting the optional parameter to play nice with the plugin mechanism.
