### ISSUE TITLE
`BIDSLayout.get()` returns a massive wall of text in interactive interpreters

### ISSUE THREAD

**Issue by pvandyken** [ANCPLabOldenburg/ancp-bids#59]
`BIDSLayout.get()` currently returns a simple dict containing all the information a user may want to query. While I believe this is *generally* the correct behaviour (cf #29), the unfortunate side effect in an interactive console (e.g. ipython) is getting a massive, unusable wall of text when I call `BIDSLayout.get()` on even a few subjects. In `pybids`, the data is wrapped in classes with easy to digest `repr` (showing the file path).

As a more general solution, I would suggest transitioning to a slotted dataclass approach. The performance is roughly equivalent to dicts, and memory usage is better. You'll also get way better control over output, along with built in typing and intellisense, which is super helpful for development. Python has the builtin `dataclass` module, and there's also the wonderful [`attrs`](https://www.attrs.org/en/stable/) library. Although `Models` and all of its child classes are currently implemented as dicts, the current structure looks super clean and I don't think a migration would be too laborious (although I'm hardly intimate with the codebase). At any rate, it would increase maintainability, saving time long term.

**Comment by erdalkaraca** [comment]
@pvandyken thanks for the suggestion

It would be easily fixable as the `__repr__()` of the base class Model would just have to be adapted to shorten the `dict.__repr__()` string.

There is also #46 to use dataclasses instead of properties, but I have not yet experimented much with that idea.

**Comment by pvandyken** [comment]
Ah, apologies for the overlapping issue. At any rate, the title of the issue, to me, is the more important thing here, and any means of limiting the text output to something useful would be great.

**Comment by erdalkaraca** [comment]
@pvandyken the base Model.__repr__ method is now overridden to summarize the object using only set simple (no lists/dicts) properties.
