### ISSUE TITLE
Provide convenience function for entities of derivative

### ISSUE THREAD

**Issue by AaronReer** [ANCPLabOldenburg/ancp-bids#63]
At the moment one has to add every entity to the derivative via the artifact.add_entity fucntion before writing it. However it would be great to provide functionality which writes every entity from the original (raw) file (data file that the computaion was run on to create the respective derivative) to the derivative such that one would only have to add the desc entity before writing derivatives. This would be great especially since derivatives in BIDS have to contain the same entities as the raw data, so this would be in compliance with the standard.

**Comment by erdalkaraca** [comment]
@AaronReer there is no formal link from an arbitrarily defined derivative file and its origin. What could be done is update the entities from the origin and overwrite existing entities, example:

```
deriv_artifact = folder.create_artifact(origin=existing_raw_artifact)
deriv_artifact.add_entity(desc='mydesc')
```

**Comment by erdalkaraca** [comment]
@AaronReer this functionality is now available, have a look at the following unit test to see how to use it:

```
    def test_create_artifact_with_raw(self):
        test_ds = load_dataset(DS005_SMALL2_DIR)
        sub01_json = test_ds.query(sub='01', suffix='bold', extension='.json')[0]
        derivative_folder = test_ds.create_derivative(name="unit-test")
        deriv_artifact = derivative_folder.create_artifact(raw=sub01_json)
        deriv_artifact.add_entities(desc='unittest')
        self.assertEqual("01", deriv_artifact.get_entity("sub"))
        self.assertEqual("mixedgamblestask", deriv_artifact.get_entity("task"))
        self.assertEqual(1, deriv_artifact.get_entity("run"))
        self.assertEqual("unittest", deriv_artifact.get_entity("desc"))
```
