### ISSUE TITLE
Some issues on writing derivatives

### ISSUE THREAD

**Issue by erdalkaraca** [ANCPLabOldenburg/ancp-bids#65]
- entities must not be repeated or appear more than one time
- error when using run=1 (int value instead of str)

**Comment by erdalkaraca** [comment]
@Evgeniia-G the issues you reported are now fixed

you can upgrade ancpBIDS by revision as there is no new package for this change:

pip install -U git+https://github.com/ANCPLabOldenburg/ancp-bids.git@8ea120d

**Comment by Evgeniia-G** [comment]
It seems to be working fine now.  Thank you!
