### ISSUE TITLE
No `entities_` attribute in self.schema.EntityEnum

### ISSUE THREAD

**Issue by adelavega** [ANCPLabOldenburg/ancp-bids#66]
https://github.com/ANCPLabOldenburg/ancp-bids/blob/1710085c600c172999fb6e4336050bc9867de3b1/ancpbids/pybids_compat.py#L80

This fails because EntityEnum no longer has a `entity_` attribute. 

I assume the idea here is to filter a file's entities by those supported by the schema?

**Comment by erdalkaraca** [comment]
@adelavega good catch! That branch (at line 80) was not covered by any unit tests, so missed that line as part of the last refactoring

**Comment by erdalkaraca** [comment]
> https://github.com/ANCPLabOldenburg/ancp-bids/blob/1710085c600c172999fb6e4336050bc9867de3b1/ancpbids/pybids_compat.py#L80
> 
> This fails because EntityEnum no longer has a `entity_` attribute.
> 
> I assume the idea here is to filter a file's entities by those supported by the schema?

a call to `get_metadata(include_entities=True)` merges all found entities (supported by the schema) into the resulting/returned dict... this was to mimic PyBIDS' get_metadata(include_entities=True)

**Comment by adelavega** [comment]
Question: Does this have to be updated in pybids as well? I'm a bit confused as to whether the development is happening here or in pybids for the `BIDSLayoutV2` compatibility layer

**Comment by erdalkaraca** [comment]
@adelavega there is a warning in that module:

https://github.com/ANCPLabOldenburg/ancp-bids/blob/1710085c600c172999fb6e4336050bc9867de3b1/ancpbids/pybids_compat.py#L14

Once, the PR in PyBIDS is done, I will remove this module in ancpBIDS.

> Question: Does this have to be updated in pybids as well? I'm a bit confused as to whether the development is happening here or in pybids for the `BIDSLayoutV2` compatibility layer. I see you said it would happen in `pybids`, can you push a similar push to your PR over there then? Thanks

**Comment by erdalkaraca** [comment]
@adelavega removed ancpBIDS' BIDSLayout and added a reference to PyBIDS

**Comment by erdalkaraca** [comment]
reference == README.md
