### ISSUE TITLE
Return true absolute path

### ISSUE THREAD

**Issue by adelavega** [ANCPLabOldenburg/ancp-bids#69]
ancp-bids function `get_absolute_path` return the path relative to the bids root.

this is problematic for a few reasons:
- first, as far as I'm aware in python convention "absolute path" refers to the true absolute path relatively the filesystem, so i think this function is a bit of a misnomer
- second, it's convenient to be able to get a file's absolute path to do things with it in downstream pipelines
- third, to implement out-of-folder derivatives, we will need true absolute paths

**Comment by erdalkaraca** [comment]
Fixed, File.get_absolute_path() now ensures absolute path by calling os.path.abspath(...)

Previously, it only concatenated the dataset path given to it, i.e. BIDSLayout(ds_path)

**Comment by adelavega** [comment]
Great, thank you!
