### ISSUE TITLE
drop auto build for Python 3.6

### ISSUE THREAD

**Issue by erdalkaraca** [ANCPLabOldenburg/ancp-bids#70]
@effigies @adelavega does pybids intend to support Python 3.6? it seems github builder has dropped support for 3.6

considering removing 3.6 from ancpbids as well

**Comment by effigies** [comment]
3.6 is end of life. We've dropped it. Many tools have dropped support for 3.7 already as it goes EOL in the next several months.

**Comment by erdalkaraca** [comment]
removed 3.6 from build pipeline and added 3.11
