### ISSUE TITLE
Long form entities for Artifact.get_entities()

### ISSUE THREAD

**Issue by adelavega** [ANCPLabOldenburg/ancp-bids#75]
Would it be possible to return "long-form" entities for `Artifact.get_entities()`?

Otherwise, I think I would have to keep track of the `Dataset` object in order to convert the entities output by `Artifact` into long form in pybids.

**Comment by erdalkaraca** [comment]
@adelavega get_entities() has now long_form=True by default, I have adapterd the unit tests accordingly
