### ISSUE TITLE
query_entities(scope='derivatives') - unexpected results

### ISSUE THREAD

**Issue by Evgeniia-Gapontseva** [ANCPLabOldenburg/ancp-bids#82]
ancpbids Version: 0.2.4

When I use query_entities(scope='derivatives') I expect to get only the entities that belong to derivatives, right?
Instead, I receive all the entities of a data set (so it probably takes them from raw, not derivs).

Example:
```
dataset_path = '.../ds003483'
dataset = ancpbids.load_dataset(dataset_path)
entities = dataset.query_entities(scope='derivatives')

print(entities)

Output:
{'subject': {'026', '017', '012', '009', '018', '020', '023', '027', '028', '015', '021', '022', '025', '016', '019', '031', '024', '030', '014', '013'}, 'session': {'1'}, 'task': {'induction', 'deduction'}, 'run': {1}, 'description': {'STDs', 'REPORT', 'Muscle', 'Sensors', 'SimpleMetrics', 'ECGs', 'epochs', 'ReportStrings', 'EOGs', 'PSDs'}}
```

This will give me all the raw entities of a data set: all subs, taks, runs...
While in the derivatives folder of this data set, I only have tsv files calculated for 1 subject, 1 task, with different descriptions.

I would like to either request correction of this function or instruction on how to use it to only get entities of derivatives.

**Comment by erdalkaraca** [comment]
I cannot reproduce that behavior: are you sure there are no files which contain other subjects that you do not expect? Also check for hidden folders or temp folders of any tools you ran previously.

**Comment by Evgeniia-Gapontseva** [comment]
> are you sure there are no files which contain other subjects that you do not expect? 

You were actually right about that, apologies!

In the folder derivatives I got 2 subfolders: MEGQC (what I m interested in) and  Preprocessing (other derivs). I didn't notice the second folder. 

Maybe you know a way how to do the following:
I need to get all the entities of the derivatives only from my .../derivatives/MEGQC/calculation folder? I don't need the entities from other derivatives (not interested Preprocessing). Is there a way to specify this with ancpbids?

In .../derivatives/MEGQC/calculation folder I save tsvs with calculated derivatives that can be plotted.
In the next step, I give the user a selector - which of these entities he wants to plot: subject, task, run, etc. But I want to only show him the selection of what exists in MEGQC/calculation folder and not all the other unrelated derivs.

**Comment by erdalkaraca** [comment]
`query_entities(scope="derivatives/MEGQC/calculation")` should do what you need

**Comment by Evgeniia-Gapontseva** [comment]
Ah cool! I didn't realize you could put the relative path into scope. I thought you could only put 'derivatives' or 'raw'.
It works, thanks!

**Comment by erdalkaraca** [comment]
Yeah, kind of hidden feature :-)
